# Docker Compose 파일 형식 버전
version: '3.8'

# 이 파일로 실행할 서비스(컨테이너)들의 목록
services:
  # 1. word-service 정의
  word-service:
    build:
      context: .
      dockerfile: word-service/Dockerfile
    ports:
      - "8081:8080"      # 내 컴퓨터의 8081 포트를 컨테이너의 8080 포트와 연결
    environment:
      # word-service 실행에 필요한 환경 변수
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/word_service_db
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db               # 'db' 서비스가 먼저 실행된 후에 실행되도록 순서 지정

  # 2. user-service 정의
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/user_service_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=your_password
    depends_on:
      - db

  # 3. 데이터베이스 서비스 정의 (MySQL)
  db:
    image: mysql:8.0      # MySQL 8.0 공식 이미지를 사용
    ports:
      - "3306:3306"      # 내 컴퓨터의 3306 포트를 컨테이너의 3306 포트와 연결
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=word_service_db,user_service_db # 실행 시 생성할 DB 스키마 목록
    volumes:
      - db-data:/var/lib/mysql # 데이터를 컴퓨터에 저장하여 컨테이너가 꺼져도 유지

# Docker가 관리하는 데이터 저장 공간(볼륨) 정의
volumes:
  db-data: