openapi: 3.0.1
info:
  title: 찍고 말해 API
  version: "1.0.0"
  description: |
    Lambda Squirrel 프로젝트 REST API 문서입니다.  
    WebSocket API는 별도 OpenAPI 3.1 문서로 관리됩니다.
  contact:
    name: Lambda Squirrel
    email: jungjunyoung1019@gmail.com

servers:
  - url: https://fzsnpt9u2g.execute-api.us-east-1.amazonaws.com/dev
    description: 개발 서버

tags:
  - name: User
    description: 사용자 관련 API
  - name: ShortForm
    description: 숏폼 콘텐츠 관련 API

paths:
  /signUp:
    post:
      tags: [User]
      summary: 회원가입
      description: 사용자 닉네임과 성별을 등록합니다.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [nickname, gender]
              properties:
                nickname:
                  type: string
                  example: "테스트 유저"
                gender:
                  type: string
                  example: "male"
      responses:
        "200":
          description: 성공적으로 회원가입 완료
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User created successfully."
                  uuid:
                    type: string
                    format: uuid
                    example: "65bad05d-200f-415b-a26d-cbb2709d65f4"
      security: []
  
  /short-form/themes:
    get:
      tags: [ShortForm]
      summary: 숏폼 테마 목록 조회
      security:
        - lambda-squirrel-authorizer: []
      responses:
        "200":
          description: 성공적으로 테마 목록 조회
          content:
            application/json:
              schema:
                type: object
                properties:
                  themeList:
                    type: array
                    items:
                      type: object
                      properties:
                        themeId:
                          type: string
                          example: "cafe"
                        description:
                          type: string
                          example: "카페에서 주문 대화 연습하기"

  /short-form/videos/{lang}/{themeId}:
    get:
      tags: [ShortForm]
      summary: 특정 테마 영상 목록 조회
      parameters:
        - name: lang
          in: path
          required: true
          description: 언어 코드
          schema:
            type: string
            example: "jp-male"
        - name: themeId
          in: path
          required: true
          description: 테마 ID
          schema:
            type: string
            example: "cafe"
      responses:
        "200":
          description: 영상 목록 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  videos:
                    type: array
                    items:
                      type: object
                      properties:
                        videoId:
                          type: string
                          example: "cafe#1"
                        title:
                          type: string
                          example: "카페에서 주문하기"
                        s3Url:
                          type: string
                          example: "https://s3.amazonaws.com/.../cafe_01.mp4"
      security:
        - lambda-squirrel-authorizer: []

components:
  securitySchemes:
    lambda-squirrel-authorizer:
      type: apiKey
      name: UUID
      in: header
